---
- name: install node and npm
  hosts: civo
  tasks:
  - name: update apt and cache
    apt: update_cache=yes force_apt_get=yes cahce_valid_time=3600
  - name: Install node and npm
    apt:
      pkg:
        - node
        - npm


- name: create new linux user for node app
  hosts: civo
  tasks:
  - name: create new user
    user:
      name: "{{linux_name}}"
      comment: "{{linux_name}} admin"
      group: admin


- name: Deploy nodejs application
  hosts: civo
  become: true
  become_user: "{{linux_name}}"
  tasks:
  - name: untar the application
    unarchive:
      src: "{{location}}"
      dest: "{{user_home_dir}}"
  - name: Install dependencies
    npm:
      path: /home/{{linux_name}}/package
  - name: start the application
    command:
      chdir: /home/{{linux_name}}/package/app
      cmd: node server
    async: 1000
    poll: 0
  - name: Ensure app is running
    shell: ps aux | grep node
    register: app_status
  - debug: msg={{app_status.stdout_lines}}