---
- name: Configure nginx server
  hosts: civo
  tasks:
  - name: apt update
    apt:
      update_cache: true
  - name: install nginx
    apt:
      name: nginx
      state: latest
  - name: start nginx server
    service:
      name: nginx
      state: started  